name: Build, Release, and Publish

on:
    push:
        branches:
            - master

jobs:
    build:
        runs-on: ubuntu-latest
        strategy:
            matrix:
                include:
                    - os: linux
                      arch: amd64
                    - os: darwin
                      arch: amd64
                    - os: darwin
                      arch: arm64
                    - os: windows
                      arch: amd64
        steps:
            - uses: actions/checkout@v4
              with:
                  fetch-depth: 0

            - name: Set up Go
              uses: actions/setup-go@v4
              with:
                  go-version: "1.21"

            - name: Build Go binary
              run: |
                  GOOS=${{ matrix.os }} GOARCH=${{ matrix.arch }} go build -o bin/chapiteau-cli-${{ matrix.os }}-${{ matrix.arch }}${{ matrix.os == 'windows' && '.exe' || '' }} .

            - name: Upload binary artifact
              uses: actions/upload-artifact@v3
              with:
                  name: chapiteau-cli-${{ matrix.os }}-${{ matrix.arch }}
                  path: bin/chapiteau-cli-${{ matrix.os }}-${{ matrix.arch }}${{ matrix.os == 'windows' && '.exe' || '' }}

    release:
        needs: build
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
              with:
                  fetch-depth: 0

            - name: Calculate version
              id: semver
              uses: paulhatch/semantic-version@v5.3.0
              with:
                  tag_prefix: "v"
                  major_pattern: "BREAKING CHANGE:"
                  minor_pattern: "feat:"

            - name: Create Release
              id: create_release
              uses: actions/create-release@v1
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
              with:
                  tag_name: v${{ steps.semver.outputs.version }}
                  release_name: Release v${{ steps.semver.outputs.version }}
                  draft: false
                  prerelease: false

            - name: Download all workflow run artifacts
              uses: actions/download-artifact@v3

            - name: Attach binaries to release
              uses: actions/upload-release-asset@v1
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
              with:
                  upload_url: ${{ steps.create_release.outputs.upload_url }}
                  asset_path: ./chapiteau-cli-*/*
                  asset_name: chapiteau-cli-${{ matrix.os }}-${{ matrix.arch }}${{ matrix.os == 'windows' && '.exe' || '' }}
                  asset_content_type: application/octet-stream

    publish-npm:
        needs: release
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4

            - name: Set up Node.js
              uses: actions/setup-node@v4
              with:
                  node-version: "18"
                  registry-url: "https://registry.npmjs.org"

            - name: Update package.json version
              run: |
                  npm version ${{ needs.release.outputs.version }} --no-git-tag-version

            - name: Publish to npm
              run: npm publish
              env:
                  NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
